export type GeneratedEnglishQuestion =
  | {
      id: number
      type: 'single_choice'
      prompt: string
      options: Record<string, string>
      correctOption: string
      skill: string
    }
  | {
      id: number
      type: 'writing'
      prompt: string
      wordLimit: string
      bullets: string[]
      checklist: string[]
      skill: string
    }

export type GeneratedEnglishSection = {
  id: string
  title: string
  mode: 'reading' | 'writing'
  sourceNote: string
  passage?: string[]
  questions: GeneratedEnglishQuestion[]
}

type ReadingBlueprint = {
  id: string
  title: string
  place: string
  actor: string
  project: string
  problem: string
  action: string
  obstacle: string
  evidence: string
  result: string
  broaderLesson: string
  vocabWord: string
  vocabMeaning: string
  wrongDetail: string
  tone: string
}

const readingBlueprints: ReadingBlueprint[] = [
  {
    id: 'library-hours',
    title: 'The Library After Dark',
    place: 'a university library',
    actor: 'the student council',
    project: 'midnight opening during exam season',
    problem: 'many students had no quiet place to revise after classes or work shifts',
    action: 'introduced computer booking, volunteer monitors and a clear code of conduct',
    obstacle: 'the heating system was unreliable and the late-shift librarians became exhausted',
    evidence: 'the reading rooms were full every evening during the trial month',
    result: 'the trial was extended while the university looked for extra staff',
    broaderLesson: 'access to study space matters only when it is supported by order and planning',
    vocabWord: 'inadequate',
    vocabMeaning: 'not good enough',
    wrongDetail: 'the library replaced all librarians with students',
    tone: 'balanced and practical',
  },
  {
    id: 'repair-cafe',
    title: 'The Repair Cafe',
    place: 'a former bakery near the city centre',
    actor: 'a group of retired volunteers',
    project: 'a weekly repair cafe for household objects',
    problem: 'people threw away useful items because they lacked basic repair skills',
    action: 'sat visitors beside volunteers who explained how to mend lamps, jackets and bicycles',
    obstacle: 'some appliances were too dangerous or too expensive to repair',
    evidence: 'teenagers began returning with notebooks to record what they had learned',
    result: 'the cafe became a popular lesson in patience and responsible consumption',
    broaderLesson: 'repairing objects can also repair people’s relationship with waste',
    vocabWord: 'mend',
    vocabMeaning: 'repair',
    wrongDetail: 'the cafe sold imported appliances at a discount',
    tone: 'hopeful and approving',
  },
  {
    id: 'remote-work',
    title: 'Remote Work With Boundaries',
    place: 'a software company with employees in six countries',
    actor: 'the human-resources team',
    project: 'a healthier remote-work policy',
    problem: 'employees enjoyed flexibility but felt pressure to be constantly available',
    action: 'set core hours, meeting-free afternoons and a rule against late-night messages',
    obstacle: 'some managers confused visibility online with real productivity',
    evidence: 'project deadlines improved after teams began protecting focused work time',
    result: 'remote work became more sustainable and less exhausting',
    broaderLesson: 'freedom works best when clear limits protect people’s time',
    vocabWord: 'sustainable',
    vocabMeaning: 'able to continue successfully',
    wrongDetail: 'the company required everyone to return to the office every day',
    tone: 'analytical and balanced',
  },
  {
    id: 'street-museum',
    title: 'A Museum Without Walls',
    place: 'a small coastal town',
    actor: 'the local curator',
    project: 'a street museum using signs, photographs and residents’ memories',
    problem: 'the town museum closed for repairs and risked losing public attention',
    action: 'invited residents to lend letters, photographs and stories from family albums',
    obstacle: 'neighbours often remembered the same event in different ways',
    evidence: 'shop windows filled with old pictures and teenagers interviewed grandparents',
    result: 'the outdoor exhibition remained after the museum building reopened',
    broaderLesson: 'history becomes stronger when a community helps tell it',
    vocabWord: 'overwhelming',
    vocabMeaning: 'very large and impressive',
    wrongDetail: 'the exhibition was built around expensive foreign paintings',
    tone: 'warm and appreciative',
  },
  {
    id: 'school-garden',
    title: 'The School Garden',
    place: 'an urban secondary school',
    actor: 'a biology teacher and her students',
    project: 'a vegetable garden in an unused courtyard',
    problem: 'students knew facts about ecosystems but rarely saw them working in real life',
    action: 'planted herbs, recorded insect visits and donated vegetables to a local kitchen',
    obstacle: 'the first plants suffered because the watering schedule was unclear',
    evidence: 'attendance in the lunchtime gardening club doubled by spring',
    result: 'the garden became part of science lessons and community volunteering',
    broaderLesson: 'practical learning can make abstract knowledge memorable',
    vocabWord: 'cultivate',
    vocabMeaning: 'grow and look after',
    wrongDetail: 'the courtyard was turned into a car park',
    tone: 'encouraging and informative',
  },
  {
    id: 'bike-bus',
    title: 'The Bicycle Bus',
    place: 'a neighbourhood with heavy morning traffic',
    actor: 'several parents',
    project: 'a supervised bicycle route to school',
    problem: 'children wanted to cycle but parents worried about safety',
    action: 'created fixed meeting points and rode in a visible group with adult volunteers',
    obstacle: 'drivers were impatient during the first week',
    evidence: 'the number of cars outside the school gate fell noticeably',
    result: 'the city council painted a safer cycle lane along the route',
    broaderLesson: 'small routines can change transport habits when safety is taken seriously',
    vocabWord: 'visible',
    vocabMeaning: 'easy to see',
    wrongDetail: 'children were asked to cycle alone before sunrise',
    tone: 'practical and optimistic',
  },
  {
    id: 'community-fridge',
    title: 'The Community Fridge',
    place: 'a busy market district',
    actor: 'local shop owners',
    project: 'a public fridge for unsold but safe food',
    problem: 'large amounts of bread, fruit and dairy products were being wasted daily',
    action: 'labelled donations, checked temperatures and invited residents to take what they needed',
    obstacle: 'some people first doubted whether the food would be safe',
    evidence: 'weekly waste bags behind the shops were reduced by more than half',
    result: 'the fridge became a symbol of cooperation rather than charity',
    broaderLesson: 'food waste can be reduced when trust and responsibility are shared',
    vocabWord: 'edible',
    vocabMeaning: 'safe or suitable to eat',
    wrongDetail: 'the fridge accepted only expensive restaurant meals',
    tone: 'constructive and community-minded',
  },
  {
    id: 'digital-archive',
    title: 'Saving Old Voices',
    place: 'a regional radio station',
    actor: 'two young sound engineers',
    project: 'a digital archive of old interviews',
    problem: 'recordings on fragile tapes were slowly becoming impossible to play',
    action: 'cleaned the tapes, digitised them and added searchable descriptions',
    obstacle: 'some labels were missing and voices had to be identified by listeners',
    evidence: 'families contacted the station after recognising relatives online',
    result: 'the archive became a valuable source for schools and historians',
    broaderLesson: 'technology can preserve memory when people add context to it',
    vocabWord: 'fragile',
    vocabMeaning: 'easily damaged',
    wrongDetail: 'the recordings were destroyed after being copied',
    tone: 'respectful and informative',
  },
  {
    id: 'plastic-free-canteen',
    title: 'Lunch Without Plastic',
    place: 'a large school canteen',
    actor: 'a group of eleventh graders',
    project: 'a campaign to remove single-use plastic from lunch service',
    problem: 'hundreds of forks, cups and wrappers were thrown away each day',
    action: 'tested reusable containers, deposit cups and posters explaining the change',
    obstacle: 'the first washing system was too slow for the lunch break',
    evidence: 'waste bins were weighed each Friday and the results were displayed publicly',
    result: 'plastic waste fell and younger students copied the habit',
    broaderLesson: 'environmental campaigns succeed when they measure results clearly',
    vocabWord: 'single-use',
    vocabMeaning: 'made to be used once only',
    wrongDetail: 'students were forbidden to bring lunch from home',
    tone: 'solution-focused',
  },
  {
    id: 'night-train',
    title: 'The Return of the Night Train',
    place: 'a railway line between two capitals',
    actor: 'a small transport company',
    project: 'a restored overnight train service',
    problem: 'travellers wanted a lower-emission alternative to short flights',
    action: 'renovated sleeping carriages and offered tickets that included breakfast',
    obstacle: 'old timetables had to be coordinated across three countries',
    evidence: 'most weekend compartments sold out within hours',
    result: 'other companies began considering similar routes',
    broaderLesson: 'older forms of transport can become modern again when needs change',
    vocabWord: 'renovated',
    vocabMeaning: 'repaired and improved',
    wrongDetail: 'the company replaced all trains with private jets',
    tone: 'optimistic and factual',
  },
  {
    id: 'quiet-hour',
    title: 'The Quiet Hour',
    place: 'a supermarket chain',
    actor: 'store managers and autism advocates',
    project: 'a weekly quiet shopping hour',
    problem: 'bright lights, loud music and crowded aisles made shopping stressful for some customers',
    action: 'dimmed lights, lowered scanner sounds and paused background music',
    obstacle: 'staff needed training to understand why small changes mattered',
    evidence: 'customers who had avoided shopping alone began returning regularly',
    result: 'the quiet hour was introduced in every branch',
    broaderLesson: 'accessibility often depends on noticing ordinary discomforts',
    vocabWord: 'adjustment',
    vocabMeaning: 'a small change made to improve something',
    wrongDetail: 'the shop closed to all customers for the whole day',
    tone: 'sensitive and supportive',
  },
  {
    id: 'robot-helper',
    title: 'A Robot in the Hospital',
    place: 'a children’s hospital',
    actor: 'the nursing team',
    project: 'a small delivery robot for medicine and laboratory samples',
    problem: 'nurses spent too much time walking between departments',
    action: 'programmed the robot to follow safe routes and call lifts automatically',
    obstacle: 'children kept stopping the robot to talk to it',
    evidence: 'nurses gained extra time for patients after routine deliveries were automated',
    result: 'the robot became both a tool and a friendly distraction',
    broaderLesson: 'technology is most useful when it supports rather than replaces human care',
    vocabWord: 'routine',
    vocabMeaning: 'regular and ordinary',
    wrongDetail: 'the robot made medical decisions without doctors',
    tone: 'curious and positive',
  },
  {
    id: 'language-buddies',
    title: 'Language Buddies',
    place: 'a public library',
    actor: 'immigrant residents and local teenagers',
    project: 'a conversation exchange programme',
    problem: 'newcomers needed speaking practice while teenagers wanted real-world language experience',
    action: 'paired participants for weekly conversations about school, work and traditions',
    obstacle: 'some pairs were shy during the first meetings',
    evidence: 'attendance improved when games and topic cards were added',
    result: 'participants formed friendships beyond the language sessions',
    broaderLesson: 'language learning becomes deeper when it is connected to real people',
    vocabWord: 'fluent',
    vocabMeaning: 'able to speak smoothly and easily',
    wrongDetail: 'participants were banned from discussing culture',
    tone: 'friendly and encouraging',
  },
  {
    id: 'green-roofs',
    title: 'Roofs That Breathe',
    place: 'a crowded city centre',
    actor: 'a team of young architects',
    project: 'green roofs on public buildings',
    problem: 'summer heat was becoming worse in streets covered mostly by concrete',
    action: 'planted grasses and wildflowers on flat roofs to absorb heat and rainwater',
    obstacle: 'older buildings needed safety checks before soil could be added',
    evidence: 'temperature sensors showed cooler air above the planted roofs',
    result: 'the city planned new rules encouraging roof gardens',
    broaderLesson: 'urban design can work with nature instead of against it',
    vocabWord: 'absorb',
    vocabMeaning: 'take in',
    wrongDetail: 'the roofs were painted black to attract more heat',
    tone: 'informative and forward-looking',
  },
  {
    id: 'micro-scholarships',
    title: 'Small Scholarships, Big Effects',
    place: 'a rural school district',
    actor: 'a local education foundation',
    project: 'micro-scholarships for exam preparation',
    problem: 'small costs for books and transport prevented some students from attending extra classes',
    action: 'gave modest grants directly to students with clear study plans',
    obstacle: 'families were initially embarrassed to apply',
    evidence: 'applications increased after former recipients spoke publicly',
    result: 'more students completed the preparation course and sat the final exam',
    broaderLesson: 'small financial barriers can have large educational consequences',
    vocabWord: 'modest',
    vocabMeaning: 'small but useful',
    wrongDetail: 'the grants were limited to professional athletes',
    tone: 'serious and supportive',
  },
  {
    id: 'citizen-science',
    title: 'Counting Butterflies',
    place: 'a national park',
    actor: 'citizen scientists',
    project: 'a butterfly-counting weekend',
    problem: 'researchers lacked enough data about changes in insect populations',
    action: 'trained visitors to identify common species and upload observations',
    obstacle: 'rain reduced butterfly activity on the first morning',
    evidence: 'thousands of reliable records were submitted by the end of the weekend',
    result: 'the data helped scientists compare habitats more accurately',
    broaderLesson: 'ordinary people can support research when the task is well explained',
    vocabWord: 'reliable',
    vocabMeaning: 'able to be trusted',
    wrongDetail: 'visitors were asked to catch and keep rare butterflies',
    tone: 'educational and optimistic',
  },
  {
    id: 'music-therapy',
    title: 'Songs in the Memory Ward',
    place: 'a care home',
    actor: 'a music therapist',
    project: 'personal playlists for residents with memory loss',
    problem: 'some residents found ordinary conversation confusing and tiring',
    action: 'asked families for meaningful songs and played them during calm sessions',
    obstacle: 'the same song could comfort one resident but upset another',
    evidence: 'staff noticed more eye contact and longer conversations after familiar music',
    result: 'music became part of the home’s daily care routine',
    broaderLesson: 'memory is sometimes reached through emotion before facts',
    vocabWord: 'familiar',
    vocabMeaning: 'well known',
    wrongDetail: 'all residents were forced to listen to the same playlist',
    tone: 'gentle and thoughtful',
  },
  {
    id: 'solar-school',
    title: 'The Solar School',
    place: 'a secondary school roof',
    actor: 'the physics department',
    project: 'solar panels used as a teaching tool',
    problem: 'students studied renewable energy without seeing real data from their own environment',
    action: 'installed panels and displayed live production figures in the entrance hall',
    obstacle: 'cloudy weeks made the first results less dramatic than expected',
    evidence: 'students began comparing energy output with weather reports',
    result: 'the panels reduced bills and improved science lessons',
    broaderLesson: 'data from everyday surroundings can make learning more convincing',
    vocabWord: 'renewable',
    vocabMeaning: 'naturally replaced and not used up permanently',
    wrongDetail: 'the school removed all science classes after installing panels',
    tone: 'informative and practical',
  },
  {
    id: 'book-vending',
    title: 'The Book Vending Machine',
    place: 'a metro station',
    actor: 'a city reading charity',
    project: 'a vending machine that lends short books',
    problem: 'commuters said they had no time to visit libraries',
    action: 'placed quick-read books beside ticket machines and allowed returns at any station',
    obstacle: 'some books disappeared during the first month',
    evidence: 'borrowing rose after the charity added reminder messages inside each cover',
    result: 'reading became part of short daily journeys',
    broaderLesson: 'access to books improves when they appear where people already are',
    vocabWord: 'commuters',
    vocabMeaning: 'people who travel regularly to work or school',
    wrongDetail: 'the machine sold only expensive textbooks',
    tone: 'light and positive',
  },
  {
    id: 'rainwater-playground',
    title: 'A Playground That Stores Rain',
    place: 'a flood-prone primary school',
    actor: 'landscape designers',
    project: 'a playground that temporarily stores rainwater',
    problem: 'heavy storms often flooded the school entrance',
    action: 'created shallow planted areas and surfaces that allowed water to drain slowly',
    obstacle: 'parents worried that the design would make play areas muddy',
    evidence: 'after the first storm, the entrance stayed clear and the garden filled safely',
    result: 'the playground taught children about climate adaptation',
    broaderLesson: 'public spaces can solve problems while still serving daily life',
    vocabWord: 'drain',
    vocabMeaning: 'flow away gradually',
    wrongDetail: 'the playground was permanently covered with deep water',
    tone: 'practical and reassuring',
  },
  {
    id: 'mentor-chefs',
    title: 'Cooking With Mentors',
    place: 'a community kitchen',
    actor: 'professional chefs',
    project: 'a mentoring course for unemployed young adults',
    problem: 'participants lacked confidence and recent work experience',
    action: 'taught cooking skills, teamwork and how to speak to customers',
    obstacle: 'some participants were afraid of making mistakes in front of others',
    evidence: 'confidence grew after the first public lunch service',
    result: 'several participants applied for hospitality jobs',
    broaderLesson: 'training works best when practical skills and self-belief grow together',
    vocabWord: 'hospitality',
    vocabMeaning: 'work connected with hotels, restaurants and guests',
    wrongDetail: 'the course was designed only for experienced restaurant owners',
    tone: 'supportive and realistic',
  },
  {
    id: 'wildlife-bridge',
    title: 'The Wildlife Bridge',
    place: 'a motorway cutting through woodland',
    actor: 'environmental engineers',
    project: 'a green bridge for animals',
    problem: 'deer and smaller animals were being separated by fast traffic',
    action: 'built a planted crossing over the road and guided animals towards it with fencing',
    obstacle: 'it took months before animals trusted the new route',
    evidence: 'night cameras eventually recorded foxes, deer and badgers crossing safely',
    result: 'collisions decreased and the woodland habitat became better connected',
    broaderLesson: 'infrastructure can protect movement as well as speed',
    vocabWord: 'habitat',
    vocabMeaning: 'the natural home of a plant or animal',
    wrongDetail: 'the bridge was reserved for cars during rush hour',
    tone: 'scientific and hopeful',
  },
  {
    id: 'phone-free-camp',
    title: 'A Phone-Free Camp',
    place: 'a mountain summer camp',
    actor: 'camp organisers',
    project: 'a week without personal smartphones',
    problem: 'campers spent free time online instead of noticing the place around them',
    action: 'stored phones safely and offered cameras, maps and evening games instead',
    obstacle: 'the first day was full of complaints and nervous checking for notifications',
    evidence: 'by midweek, campers were planning hikes and writing postcards',
    result: 'many said the week felt longer and more memorable',
    broaderLesson: 'disconnecting can make attention feel available again',
    vocabWord: 'notifications',
    vocabMeaning: 'alerts or messages from a device',
    wrongDetail: 'campers were prevented from contacting families in emergencies',
    tone: 'reflective and mildly humorous',
  },
  {
    id: 'pop-up-clinic',
    title: 'The Pop-Up Clinic',
    place: 'a remote island',
    actor: 'a travelling medical team',
    project: 'a monthly pop-up health clinic',
    problem: 'residents had to take a ferry for simple check-ups',
    action: 'brought nurses, basic tests and video calls with doctors to the community hall',
    obstacle: 'bad weather sometimes delayed equipment deliveries',
    evidence: 'older residents attended check-ups more regularly than before',
    result: 'minor problems were treated earlier and hospital trips decreased',
    broaderLesson: 'health care improves when distance is treated as a real barrier',
    vocabWord: 'remote',
    vocabMeaning: 'far away from main centres',
    wrongDetail: 'the clinic replaced the island school',
    tone: 'factual and compassionate',
  },
  {
    id: 'climate-theatre',
    title: 'The Climate Play',
    place: 'a youth theatre',
    actor: 'teenage actors',
    project: 'a play based on local climate stories',
    problem: 'climate change felt too abstract when discussed only through statistics',
    action: 'interviewed farmers, firefighters and grandparents before writing scenes',
    obstacle: 'the actors struggled to avoid sounding like a school lecture',
    evidence: 'audiences stayed after performances to share their own memories',
    result: 'the play made environmental change feel personal and local',
    broaderLesson: 'art can translate large issues into human experience',
    vocabWord: 'abstract',
    vocabMeaning: 'not concrete or easy to picture',
    wrongDetail: 'the script ignored local people completely',
    tone: 'thoughtful and creative',
  },
  {
    id: 'exam-breakfast',
    title: 'Breakfast Before the Exam',
    place: 'a secondary school',
    actor: 'the school nurse',
    project: 'a free breakfast club during final exams',
    problem: 'some students arrived hungry and found it difficult to concentrate',
    action: 'served simple food and created a calm space before morning exams',
    obstacle: 'students were initially embarrassed to be seen accepting help',
    evidence: 'attendance grew after the club was opened to everyone, not only those in need',
    result: 'teachers noticed calmer starts to exam days',
    broaderLesson: 'support is more effective when it protects dignity',
    vocabWord: 'dignity',
    vocabMeaning: 'self-respect',
    wrongDetail: 'the club charged high prices for breakfast',
    tone: 'caring and practical',
  },
  {
    id: 'smart-benches',
    title: 'The Smart Bench Debate',
    place: 'a renovated public square',
    actor: 'the city council',
    project: 'solar-powered benches with phone chargers',
    problem: 'the square needed seating but residents disagreed about adding technology',
    action: 'installed a few benches as a trial and collected public feedback',
    obstacle: 'critics argued that public spaces should encourage conversation, not more screen time',
    evidence: 'older residents used the benches for rest while students used the chargers after school',
    result: 'the council kept some smart benches but added ordinary wooden ones too',
    broaderLesson: 'public design must balance convenience with social purpose',
    vocabWord: 'trial',
    vocabMeaning: 'a test for a limited time',
    wrongDetail: 'all seating was removed from the square',
    tone: 'balanced and civic-minded',
  },
  {
    id: 'ocean-cleanup',
    title: 'Fishing for Plastic',
    place: 'a harbour town',
    actor: 'local fishermen',
    project: 'a scheme to bring collected sea plastic back to port',
    problem: 'nets often caught plastic waste that was thrown back because disposal was inconvenient',
    action: 'provided free bags and a dockside container for marine rubbish',
    obstacle: 'fishermen worried the extra work would slow them down',
    evidence: 'the first month filled three containers with plastic bottles, rope and packaging',
    result: 'the harbour became cleaner and the scheme attracted school visits',
    broaderLesson: 'environmental action improves when it fits existing routines',
    vocabWord: 'marine',
    vocabMeaning: 'connected with the sea',
    wrongDetail: 'fishermen were told to stop catching fish entirely',
    tone: 'practical and positive',
  },
  {
    id: 'micro-forest',
    title: 'The Tiny Forest',
    place: 'a vacant lot between apartment blocks',
    actor: 'neighbourhood volunteers',
    project: 'a dense micro-forest of native trees',
    problem: 'the area had little shade and almost no place for birds or insects',
    action: 'planted many young trees close together and protected them with mulch',
    obstacle: 'some residents feared the lot would look messy before the trees matured',
    evidence: 'within a year, birds and butterflies were regularly seen there',
    result: 'the lot became cooler, greener and more popular with families',
    broaderLesson: 'nature can return quickly when urban space is used imaginatively',
    vocabWord: 'native',
    vocabMeaning: 'naturally belonging to a place',
    wrongDetail: 'the volunteers planted only plastic trees',
    tone: 'hopeful and descriptive',
  },
  {
    id: 'library-of-things',
    title: 'The Library of Things',
    place: 'a neighbourhood library',
    actor: 'library staff',
    project: 'lending tools, cameras and camping equipment',
    problem: 'people bought items they used only once or twice',
    action: 'catalogued useful objects and taught borrowers how to use them safely',
    obstacle: 'insurance rules were more complicated than for ordinary books',
    evidence: 'the most borrowed item was a carpet cleaner used after winter floods',
    result: 'residents saved money and storage space',
    broaderLesson: 'sharing can be practical when trust is organised carefully',
    vocabWord: 'catalogued',
    vocabMeaning: 'listed and organised',
    wrongDetail: 'the library stopped lending books altogether',
    tone: 'informative and approving',
  },
  {
    id: 'silent-disco',
    title: 'The Silent Disco Solution',
    place: 'a student residence',
    actor: 'the residence committee',
    project: 'silent discos with wireless headphones',
    problem: 'weekend parties caused complaints from neighbours and students who wanted to sleep',
    action: 'gave dancers headphones and set a strict finishing time',
    obstacle: 'some students thought the idea would feel ridiculous',
    evidence: 'complaints dropped while attendance remained high',
    result: 'the committee proved that fun and respect could coexist',
    broaderLesson: 'creative compromises can solve conflicts without banning enjoyment',
    vocabWord: 'coexist',
    vocabMeaning: 'exist together at the same time',
    wrongDetail: 'all music was banned permanently',
    tone: 'light but practical',
  },
  {
    id: 'artisan-market',
    title: 'The Makers’ Market',
    place: 'an old bus depot',
    actor: 'local craftspeople',
    project: 'a monthly market for handmade goods and repair demonstrations',
    problem: 'small makers struggled to reach customers online',
    action: 'shared stalls, offered demonstrations and explained the stories behind products',
    obstacle: 'the depot was cold and unattractive during the first winter event',
    evidence: 'visitors spent more time at stalls where makers demonstrated their work',
    result: 'the market became a cultural event rather than just a place to shop',
    broaderLesson: 'people value objects more when they understand the skill behind them',
    vocabWord: 'demonstrations',
    vocabMeaning: 'practical shows of how something is done',
    wrongDetail: 'only mass-produced imported goods were allowed',
    tone: 'admiring and descriptive',
  },
  {
    id: 'forest-school',
    title: 'Lessons Under Trees',
    place: 'a woodland near a primary school',
    actor: 'early-years teachers',
    project: 'weekly outdoor lessons',
    problem: 'some children found it hard to sit still in a classroom all morning',
    action: 'used leaves, sticks and weather observations for counting, language and science tasks',
    obstacle: 'adults worried that cold weather would stop learning',
    evidence: 'teachers noticed better cooperation after outdoor sessions',
    result: 'the school invested in waterproof clothing instead of cancelling the programme',
    broaderLesson: 'learning environments can shape behaviour as much as lesson content',
    vocabWord: 'cooperation',
    vocabMeaning: 'working together',
    wrongDetail: 'children were left outside without adult supervision',
    tone: 'encouraging and educational',
  },
  {
    id: 'accessible-beach',
    title: 'A Beach for Everyone',
    place: 'a popular seaside resort',
    actor: 'a disability rights group',
    project: 'accessible paths and floating wheelchairs',
    problem: 'soft sand prevented many visitors from reaching the water',
    action: 'installed temporary beach mats and trained lifeguards to assist safely',
    obstacle: 'some businesses questioned whether the investment would be used enough',
    evidence: 'families travelled from other towns after hearing about the changes',
    result: 'the resort gained visitors and a stronger sense of inclusion',
    broaderLesson: 'accessibility benefits more people than planners first imagine',
    vocabWord: 'temporary',
    vocabMeaning: 'lasting for a limited time',
    wrongDetail: 'the beach was closed to families with children',
    tone: 'inclusive and positive',
  },
  {
    id: 'podcast-history',
    title: 'History in Headphones',
    place: 'a history classroom',
    actor: 'a group of final-year students',
    project: 'podcast episodes about local historical figures',
    problem: 'textbook chapters felt distant from students’ own lives',
    action: 'researched archives, interviewed experts and wrote short audio scripts',
    obstacle: 'students had to learn how to check facts before recording dramatic scenes',
    evidence: 'younger pupils listened to the episodes while walking past the places described',
    result: 'local history became easier to remember and discuss',
    broaderLesson: 'storytelling can make research more accessible without making it less serious',
    vocabWord: 'archives',
    vocabMeaning: 'collections of historical records',
    wrongDetail: 'students were told to invent facts for entertainment',
    tone: 'engaged and educational',
  },
  {
    id: 'anti-loneliness',
    title: 'The Conversation Table',
    place: 'a busy cafe',
    actor: 'the cafe owner',
    project: 'a table reserved for people willing to talk to strangers',
    problem: 'many regular customers lived alone and rarely had casual conversations',
    action: 'placed a simple sign on one table and trained staff to introduce the idea gently',
    obstacle: 'some customers feared the table would feel forced or embarrassing',
    evidence: 'regulars began arranging to meet there at the same time each week',
    result: 'the table became a low-pressure way to reduce loneliness',
    broaderLesson: 'social connection can start with small invitations',
    vocabWord: 'casual',
    vocabMeaning: 'informal and relaxed',
    wrongDetail: 'customers had to pay extra to sit at the table',
    tone: 'kind and observant',
  },
  {
    id: 'urban-bees',
    title: 'Bees on the Balcony',
    place: 'an apartment block',
    actor: 'a residents’ association',
    project: 'pollinator boxes and balcony flowers',
    problem: 'the courtyard looked tidy but offered little food for insects',
    action: 'planted native flowers and added small bee hotels away from windows',
    obstacle: 'residents first confused solitary bees with aggressive wasps',
    evidence: 'an information evening reduced fear and increased participation',
    result: 'the courtyard became more colourful and ecologically useful',
    broaderLesson: 'environmental action often begins by correcting misunderstandings',
    vocabWord: 'pollinator',
    vocabMeaning: 'an insect or animal that helps plants reproduce',
    wrongDetail: 'residents released dangerous insects inside apartments',
    tone: 'informative and reassuring',
  },
  {
    id: 'mobile-makerspace',
    title: 'The Mobile Makerspace',
    place: 'villages without technology labs',
    actor: 'a regional education charity',
    project: 'a van carrying 3D printers, tools and robotics kits',
    problem: 'rural students had fewer chances to try modern design technology',
    action: 'visited schools for two-day workshops focused on solving local problems',
    obstacle: 'internet access was unreliable in several villages',
    evidence: 'students designed simple devices for farms, libraries and sports clubs',
    result: 'teachers requested training so projects could continue after the van left',
    broaderLesson: 'access to technology matters most when it is linked to real needs',
    vocabWord: 'unreliable',
    vocabMeaning: 'not always working or trustworthy',
    wrongDetail: 'the van visited only private city schools',
    tone: 'innovative and practical',
  },
  {
    id: 'sports-inclusion',
    title: 'A Team With New Rules',
    place: 'a community sports club',
    actor: 'the junior coaches',
    project: 'mixed-ability training sessions',
    problem: 'beginners often quit because matches were dominated by experienced players',
    action: 'changed scoring rules so teamwork and improvement counted alongside goals',
    obstacle: 'competitive players initially disliked the slower pace',
    evidence: 'attendance increased when players began mentoring each other',
    result: 'the club became more inclusive without losing ambition',
    broaderLesson: 'competition can motivate people when it does not humiliate beginners',
    vocabWord: 'inclusive',
    vocabMeaning: 'welcoming different kinds of people',
    wrongDetail: 'experienced players were permanently removed from the club',
    tone: 'fair-minded and encouraging',
  },
  {
    id: 'street-lighting',
    title: 'Lighting the Walk Home',
    place: 'a path between a station and a college',
    actor: 'student representatives',
    project: 'safer evening lighting',
    problem: 'students felt unsafe walking home after winter classes',
    action: 'mapped dark areas, collected reports and presented them to the council',
    obstacle: 'officials first argued that the path was not used enough',
    evidence: 'a student survey showed hundreds used the route every week',
    result: 'new lights were installed and evening attendance improved',
    broaderLesson: 'local evidence can turn a complaint into a convincing proposal',
    vocabWord: 'survey',
    vocabMeaning: 'a set of questions used to collect information',
    wrongDetail: 'students asked for the station to be closed',
    tone: 'clear and civic',
  },
  {
    id: 'zero-waste-shop',
    title: 'The Zero-Waste Shop',
    place: 'a small high street shop',
    actor: 'two sisters',
    project: 'selling food without disposable packaging',
    problem: 'customers wanted to reduce waste but found supermarket packaging unavoidable',
    action: 'sold grains, soap and cleaning liquids into customers’ own containers',
    obstacle: 'some shoppers assumed the system would be expensive and inconvenient',
    evidence: 'loyal customers returned after realising they could buy only the amount needed',
    result: 'the shop survived by focusing on advice as much as products',
    broaderLesson: 'sustainable habits spread when they are made simple and personal',
    vocabWord: 'disposable',
    vocabMeaning: 'intended to be thrown away after use',
    wrongDetail: 'the shop wrapped every product in extra plastic',
    tone: 'practical and mildly persuasive',
  },
  {
    id: 'memory-map',
    title: 'Mapping Childhood Games',
    place: 'an old neighbourhood park',
    actor: 'a group of sociology students',
    project: 'a memory map of games once played in the park',
    problem: 'renovation plans ignored how different generations had used the space',
    action: 'interviewed residents and marked former play areas on a large public map',
    obstacle: 'memories sometimes contradicted the official planning documents',
    evidence: 'the map revealed that one empty corner had once been the busiest meeting point',
    result: 'designers added flexible open space instead of filling the park with equipment',
    broaderLesson: 'planning improves when emotional history is treated as evidence',
    vocabWord: 'contradicted',
    vocabMeaning: 'said the opposite of',
    wrongDetail: 'students refused to speak to older residents',
    tone: 'reflective and analytical',
  },
  {
    id: 'exam-app',
    title: 'The Revision App',
    place: 'a final-year English class',
    actor: 'three classmates',
    project: 'a revision app based on short daily tasks',
    problem: 'students left exam preparation until the final stressful weeks',
    action: 'created reminders, mini reading tasks and writing checklists',
    obstacle: 'the first version rewarded speed more than accuracy',
    evidence: 'practice improved after the app began explaining wrong answers',
    result: 'students used it as a habit builder rather than a last-minute solution',
    broaderLesson: 'digital tools help learning when feedback matters more than points',
    vocabWord: 'accuracy',
    vocabMeaning: 'correctness',
    wrongDetail: 'the app removed explanations to make practice faster',
    tone: 'evaluative and practical',
  },
  {
    id: 'community-orchestra',
    title: 'The Community Orchestra',
    place: 'a town concert hall',
    actor: 'a young conductor',
    project: 'an orchestra mixing beginners and experienced musicians',
    problem: 'many adults regretted giving up instruments when they were younger',
    action: 'arranged music with easier and harder parts so everyone could contribute',
    obstacle: 'early rehearsals sounded uneven and some players lost confidence',
    evidence: 'the final concert sold out because families wanted to support the experiment',
    result: 'the orchestra continued as a space for learning rather than perfection',
    broaderLesson: 'shared culture can value participation as well as excellence',
    vocabWord: 'contribute',
    vocabMeaning: 'add something to a shared effort',
    wrongDetail: 'only professional musicians were allowed to perform',
    tone: 'warm and encouraging',
  },
  {
    id: 'library-cat',
    title: 'The Library Cat',
    place: 'a village library',
    actor: 'the librarian',
    project: 'allowing a stray cat to remain in the reading room',
    problem: 'the library was quiet but felt unwelcoming to younger children',
    action: 'created rules for feeding the cat and a reading corner named after it',
    obstacle: 'one parent worried about allergies, so the cat-free area was clearly marked',
    evidence: 'children began borrowing books to read aloud near the cat’s basket',
    result: 'the library gained a friendlier identity without becoming chaotic',
    broaderLesson: 'small symbols can change how public places feel',
    vocabWord: 'stray',
    vocabMeaning: 'without a home or owner',
    wrongDetail: 'the cat was allowed to damage books freely',
    tone: 'gentle and humorous',
  },
  {
    id: 'local-newsletter',
    title: 'The Printed Newsletter',
    place: 'a district where many elderly residents live',
    actor: 'two journalism students',
    project: 'a printed monthly newsletter',
    problem: 'important local announcements were posted online but missed by people without internet',
    action: 'summarised council news, bus changes and community events in plain language',
    obstacle: 'printing costs had to be covered by small local advertisements',
    evidence: 'residents brought annotated copies to public meetings',
    result: 'more people took part in decisions affecting the neighbourhood',
    broaderLesson: 'communication is only effective when it reaches the people concerned',
    vocabWord: 'annotated',
    vocabMeaning: 'marked with notes',
    wrongDetail: 'the newsletter was available only through a smartphone app',
    tone: 'civic and respectful',
  },
  {
    id: 'science-cafe',
    title: 'Science in the Cafe',
    place: 'a crowded town cafe',
    actor: 'university researchers',
    project: 'short public science talks followed by questions',
    problem: 'many people felt science was distant and difficult to discuss',
    action: 'explained research in everyday language over informal evening meetings',
    obstacle: 'speakers had to avoid both oversimplifying and using technical jargon',
    evidence: 'audience questions became more detailed after the first sessions',
    result: 'the cafe became a bridge between researchers and the community',
    broaderLesson: 'expert knowledge becomes more useful when conversation is possible',
    vocabWord: 'jargon',
    vocabMeaning: 'special words used by a profession or group',
    wrongDetail: 'questions from the audience were forbidden',
    tone: 'open and educational',
  },
  {
    id: 'school-radio',
    title: 'The School Radio Station',
    place: 'a secondary school corridor',
    actor: 'students from different year groups',
    project: 'a short radio broadcast during Friday lunch',
    problem: 'school notices were ignored when they appeared only on boards',
    action: 'mixed announcements with interviews, music reviews and exam tips',
    obstacle: 'the first broadcasts were too long and interrupted lunchtime clubs',
    evidence: 'listening improved when episodes were limited to eight minutes',
    result: 'students became better informed and more willing to share achievements',
    broaderLesson: 'communication works when the audience’s attention is respected',
    vocabWord: 'broadcast',
    vocabMeaning: 'a radio or online programme sent to listeners',
    wrongDetail: 'the station broadcast continuously during lessons',
    tone: 'lively and practical',
  },
  {
    id: 'shared-workshop',
    title: 'The Shared Workshop',
    place: 'an empty warehouse',
    actor: 'young furniture designers',
    project: 'a cooperative workshop with shared machines',
    problem: 'independent makers could not afford expensive equipment alone',
    action: 'paid small membership fees and booked machines through an online calendar',
    obstacle: 'members had to agree on safety rules and cleaning responsibilities',
    evidence: 'new collaborations appeared between people who had previously worked alone',
    result: 'the workshop lowered costs and created a professional community',
    broaderLesson: 'sharing resources can also create shared standards',
    vocabWord: 'cooperative',
    vocabMeaning: 'owned or organised by people working together',
    wrongDetail: 'machines were available only to one wealthy company',
    tone: 'businesslike and positive',
  },
]

function buildPassage(blueprint: ReadingBlueprint): string[] {
  return [
    `In ${blueprint.place}, ${blueprint.actor} started ${blueprint.project}. The reason was simple: ${blueprint.problem}. At first, the idea sounded modest, but it soon attracted attention because it dealt with a problem people recognised from daily life.`,
    `The organisers ${blueprint.action}. Their plan was not perfect immediately. ${blueprint.obstacle}. Instead of treating this as failure, they adjusted the project and collected evidence carefully. One useful sign was that ${blueprint.evidence}.`,
    `By the end of the trial, ${blueprint.result}. The experience suggested a broader lesson: ${blueprint.broaderLesson}. The project did not solve every related problem, but it showed that thoughtful local action can change behaviour when people understand its purpose.`,
  ]
}

function buildReadingQuestions(blueprint: ReadingBlueprint, startId: number): GeneratedEnglishQuestion[] {
  return [
    {
      id: startId,
      type: 'single_choice',
      prompt: `Why was ${blueprint.project} started?`,
      options: {
        A: 'Because the organisers wanted to avoid working with the public.',
        B: `Because ${blueprint.problem}.`,
        C: `Because ${blueprint.wrongDetail}.`,
        D: 'Because the project had already become unnecessary.',
      },
      correctOption: 'B',
      skill: 'detail',
    },
    {
      id: startId + 1,
      type: 'single_choice',
      prompt: 'Which difficulty did the organisers face?',
      options: {
        A: blueprint.obstacle,
        B: 'Nobody in the area noticed the project.',
        C: 'The project was completed before it began.',
        D: blueprint.wrongDetail,
      },
      correctOption: 'A',
      skill: 'detail',
    },
    {
      id: startId + 2,
      type: 'single_choice',
      prompt: 'What did the organisers do as part of their plan?',
      options: {
        A: 'They stopped collecting evidence.',
        B: `They ${blueprint.action}.`,
        C: 'They asked people to ignore the original problem.',
        D: 'They cancelled the trial after one day.',
      },
      correctOption: 'B',
      skill: 'purpose',
    },
    {
      id: startId + 3,
      type: 'single_choice',
      prompt: 'Which piece of evidence showed that the project was having an effect?',
      options: {
        A: `That ${blueprint.evidence}.`,
        B: 'That every participant lost interest immediately.',
        C: 'That the organisers refused to change anything.',
        D: `That ${blueprint.wrongDetail}.`,
      },
      correctOption: 'A',
      skill: 'evidence',
    },
    {
      id: startId + 4,
      type: 'single_choice',
      prompt: `In the passage, "${blueprint.vocabWord}" is closest in meaning to...`,
      options: {
        A: 'unnecessary or unrelated.',
        B: blueprint.vocabMeaning,
        C: 'secret and impossible to explain.',
        D: 'dangerous in every situation.',
      },
      correctOption: 'B',
      skill: 'vocabulary in context',
    },
    {
      id: startId + 5,
      type: 'single_choice',
      prompt: 'Which statement is NOT true according to the passage?',
      options: {
        A: `The project took place in ${blueprint.place}.`,
        B: `The organisers faced this difficulty: ${blueprint.obstacle}.`,
        C: `The passage says that ${blueprint.wrongDetail}.`,
        D: `The broader lesson was that ${blueprint.broaderLesson}.`,
      },
      correctOption: 'C',
      skill: 'negative detail',
    },
    {
      id: startId + 6,
      type: 'single_choice',
      prompt: 'The general tone of the passage is best described as...',
      options: {
        A: blueprint.tone,
        B: 'angry and insulting.',
        C: 'mysterious and frightening.',
        D: 'careless and confused.',
      },
      correctOption: 'A',
      skill: 'tone',
    },
    {
      id: startId + 7,
      type: 'single_choice',
      prompt: 'What can be inferred from the organisers’ reaction to the obstacle?',
      options: {
        A: 'They believed every problem should be hidden from the public.',
        B: 'They were willing to adjust the project instead of giving up.',
        C: 'They thought evidence was less useful than advertising.',
        D: 'They wanted the project to remain temporary and invisible.',
      },
      correctOption: 'B',
      skill: 'inference',
    },
    {
      id: startId + 8,
      type: 'single_choice',
      prompt: 'Which sentence best expresses the main idea of the passage?',
      options: {
        A: `A local project showed that ${blueprint.broaderLesson}.`,
        B: 'Public projects always fail when they begin with a trial.',
        C: 'Local problems cannot be improved through practical action.',
        D: 'Evidence is useful only when no one changes their behaviour.',
      },
      correctOption: 'A',
      skill: 'main idea',
    },
    {
      id: startId + 9,
      type: 'single_choice',
      prompt: 'Why does the writer mention that the project did not solve every related problem?',
      options: {
        A: 'To show that the project was a complete failure.',
        B: 'To make the evaluation realistic rather than exaggerated.',
        C: 'To suggest that the original problem was imaginary.',
        D: 'To prove that local action should never be attempted.',
      },
      correctOption: 'B',
      skill: 'author attitude',
    },
  ]
}

const selectedReadingBlueprints = readingBlueprints.slice(0, 45)

const readingSections: GeneratedEnglishSection[] = selectedReadingBlueprints.map((blueprint, index) => ({
  id: blueprint.id,
  title: `Reading Passage ${index + 1}: ${blueprint.title}`,
  mode: 'reading',
  sourceNote: 'ABCD reading comprehension: detail, inference, vocabulary, tone and main idea.',
  passage: buildPassage(blueprint),
  questions: buildReadingQuestions(blueprint, index * 10 + 1),
}))

const writingPrompts = [
  ['formal letter', 'Write a formal letter to the head teacher about creating a quiet study room at school.', ['explain why current study conditions are not suitable', 'suggest practical improvements', 'offer ways students could help organise the room']],
  ['formal letter', 'Write a formal letter of complaint to the manager of a language course you attended.', ['describe what was promised in the advertisement', 'explain what disappointed you', 'ask for compensation or another solution']],
  ['formal letter', 'Write a formal letter to your mayor suggesting how young people can help reduce food waste.', ['explain why food waste is serious', 'suggest two realistic measures', 'describe the possible positive effect']],
  ['formal letter', 'Write a formal letter to the organiser of a student conference asking for changes to the programme.', ['say which parts are not useful enough', 'suggest new activities or speakers', 'explain how the changes would benefit students']],
  ['formal letter', 'Write a formal letter to a museum director proposing more activities for teenagers.', ['explain why teenagers rarely visit', 'suggest activities that would attract them', 'offer to help promote the programme']],
  ['formal letter', 'Write a formal letter to a shop manager about being treated unfairly by a member of staff.', ['describe the situation clearly', 'explain why you were disappointed', 'ask for an apology or suitable action']],
  ['formal letter', 'Write a formal letter to the editor of a local newspaper about dangerous traffic near your school.', ['describe the problem', 'explain how it affects students', 'suggest practical safety measures']],
  ['formal letter', 'Write a formal letter to the principal asking for a school recycling system.', ['explain the current waste problem', 'suggest how recycling could be organised', 'say how students could participate']],
  ['formal letter', 'Write a formal letter to a sports centre requesting better facilities for young people.', ['describe which facilities are missing', 'explain why they are needed', 'suggest affordable improvements']],
  ['formal letter', 'Write a formal letter to a public transport company about unreliable buses.', ['describe the problem and when it happens', 'explain how it affects students', 'suggest what the company should do']],
  ['formal letter', 'Write a formal letter to a theatre manager suggesting student discounts.', ['explain why theatre is important for young people', 'suggest a discount scheme', 'describe how schools could cooperate']],
  ['formal letter', 'Write a formal letter to the head librarian asking for longer opening hours during exams.', ['explain why the current hours are inadequate', 'propose practical measures', 'express willingness to assist']],
  ['formal letter', 'Write a formal letter to a hotel manager about a disappointing school trip stay.', ['describe what was wrong with the accommodation', 'explain how it affected the group', 'request compensation or an explanation']],
  ['formal letter', 'Write a formal letter to your municipality proposing more trees in your neighbourhood.', ['describe the current problem', 'suggest where trees could be planted', 'explain the benefits for residents']],
  ['formal letter', 'Write a formal letter to an online platform about an advertisement you find inappropriate.', ['describe the advertisement', 'explain why you disapprove of it', 'suggest how it could be changed']],
  ['formal letter', 'Write a formal letter to the organiser of a volunteer project asking for more information.', ['explain why you are interested', 'ask about duties and schedule', 'say what skills you can offer']],
  ['formal letter', 'Write a formal letter to a school board about introducing career workshops.', ['explain why students need career guidance', 'suggest useful workshop topics', 'describe how local employers could help']],
  ['formal letter', 'Write a formal letter to a city library proposing a book club for teenagers.', ['explain why the club would be useful', 'suggest how meetings could be organised', 'offer ideas for attracting participants']],
  ['formal letter', 'Write a formal letter to a restaurant manager about poor service during a celebration.', ['describe what happened', 'explain why the occasion was affected', 'ask for an appropriate response']],
  ['formal letter', 'Write a formal letter to a local organisation proposing a campaign against digital addiction.', ['explain why the issue matters', 'suggest campaign activities', 'describe the expected effect on young people']],
  ['opinion essay', 'Write an essay expressing your opinion on whether schools should teach more practical life skills.', ['skills students need outside school', 'possible disadvantages of adding new subjects', 'how schools could balance theory and practice']],
  ['opinion essay', 'Write an essay expressing your opinion on whether technology is making communication better or worse.', ['advantages of instant communication', 'problems caused by online communication', 'your personal view with examples']],
  ['opinion essay', 'Write an essay expressing your opinion on what makes a good leader.', ['personal qualities', 'communication and teamwork', 'whether leadership can be learned']],
  ['opinion essay', 'Write an essay expressing your opinion on whether classic arts are still important today.', ['why literature, theatre or painting may matter', 'why some people prefer modern media', 'your own examples']],
  ['opinion essay', 'Write an essay expressing your opinion on the future of work.', ['advantages and disadvantages of technology', 'changes in workplace relationships', 'skills people will need']],
  ['opinion essay', 'Write an essay expressing your opinion on whether social media does more harm than good.', ['connection and information', 'privacy and mental health', 'responsible use']],
  ['opinion essay', 'Write an essay expressing your opinion on whether young people should volunteer.', ['benefits for the community', 'benefits for students', 'possible difficulties']],
  ['opinion essay', 'Write an essay expressing your opinion on whether exams are the best way to assess students.', ['what exams measure well', 'what they fail to show', 'possible alternatives']],
  ['opinion essay', 'Write an essay expressing your opinion on whether city life is better than life in a small town.', ['education and work opportunities', 'stress and environment', 'personal preferences']],
  ['opinion essay', 'Write an essay expressing your opinion on whether travel is the best form of education.', ['learning about cultures', 'cost and access', 'comparison with school learning']],
  ['opinion essay', 'Write an essay expressing your opinion on whether teenagers should have part-time jobs.', ['money and responsibility', 'effects on schoolwork', 'skills for the future']],
  ['opinion essay', 'Write an essay expressing your opinion on whether people rely too much on smartphones.', ['convenience', 'distraction and dependence', 'ways to use phones wisely']],
  ['opinion essay', 'Write an essay expressing your opinion on whether school uniforms are a good idea.', ['equality and discipline', 'individuality and comfort', 'your own school experience']],
  ['opinion essay', 'Write an essay expressing your opinion on whether online learning can replace classroom learning.', ['flexibility', 'motivation and social contact', 'best use of both forms']],
  ['opinion essay', 'Write an essay expressing your opinion on whether famous people should be role models.', ['positive influence', 'unrealistic expectations', 'responsibility of fans and media']],
  ['opinion essay', 'Write an essay expressing your opinion on whether environmental protection should be a school priority.', ['knowledge and habits', 'student projects', 'possible limits of school responsibility']],
  ['opinion essay', 'Write an essay expressing your opinion on whether teamwork is more important than individual talent.', ['advantages of cooperation', 'importance of personal effort', 'examples from school or sport']],
  ['opinion essay', 'Write an essay expressing your opinion on whether money is the main factor in choosing a career.', ['financial security', 'personal satisfaction', 'long-term development']],
  ['opinion essay', 'Write an essay expressing your opinion on whether people should read more books in the digital age.', ['imagination and concentration', 'competition from digital media', 'ways to encourage reading']],
  ['opinion essay', 'Write an essay expressing your opinion on whether failure is necessary for success.', ['lessons from mistakes', 'confidence and persistence', 'examples from personal experience']],
  ['story', 'Write a story ending with: "That was the moment I realised I had been completely wrong."', ['set the scene clearly', 'include a misunderstanding or surprise', 'make the ending meaningful']],
  ['story', 'Write a story beginning with: "If I had checked the message one minute earlier, everything would have been different."', ['continue from the given first sentence', 'create tension or a problem', 'finish with a clear result']],
  ['story', 'Write a story ending with: "I still cannot believe my luck."', ['include a problem at the beginning', 'show how the situation changed', 'use the given ending exactly']],
  ['story', 'Write a story beginning with: "The train doors closed, and only then did I notice the bag on the seat."', ['create a clear setting', 'include suspense or a decision', 'end with a result']],
  ['story', 'Write a story ending with: "No one in the room knew whether to laugh or cry."', ['build up to an unexpected moment', 'include at least two characters', 'make the final sentence logical']],
  ['description', 'Describe a person who helped you change your opinion about something important.', ['describe the person and your first impression', 'explain what happened', 'say how your opinion changed']],
  ['description', 'Describe a place in your town that deserves more attention.', ['describe what the place looks like', 'explain why it matters', 'suggest how it could be improved']],
  ['description', 'Describe a memorable school event.', ['explain when and where it happened', 'describe the atmosphere', 'say why you still remember it']],
  ['description', 'Describe a time when technology helped you solve a problem.', ['describe the problem', 'explain how technology helped', 'say what you learned']],
  ['description', 'Describe a person whose work you admire.', ['describe what the person does', 'explain their important qualities', 'say how they inspire others']],
] as const

const writingSections: GeneratedEnglishSection[] = [
  {
    id: 'writing',
    title: 'Writing Practice: 50 DZI-Style Prompts',
    mode: 'writing',
    sourceNote: 'Formal letters, opinion essays, stories and descriptions with DZI-style word limits and bullet prompts.',
    questions: writingPrompts.map(([skill, prompt, bullets], index) => {
      const isFormalLetter = skill === 'formal letter'
      const isEssay = skill === 'opinion essay'
      return {
        id: 451 + index,
        type: 'writing',
        prompt,
        wordLimit: isFormalLetter ? '120-130 words' : isEssay ? '200-220 words' : '160-170 words',
        bullets: [...bullets],
        checklist: isFormalLetter
          ? ['formal greeting and ending', 'clear reason for writing', 'all bullet points covered']
          : isEssay
            ? ['clear opinion', 'arguments and examples', 'logical paragraphing and conclusion']
            : ['clear sequence or description', 'appropriate past tenses and linking words', 'task wording followed exactly'],
        skill,
      }
    }),
  },
]

export const generatedEnglishMaterialSections: GeneratedEnglishSection[] = [
  ...readingSections,
  ...writingSections,
]

export const generatedEnglishQuestionCount = generatedEnglishMaterialSections.reduce(
  (total, section) => total + section.questions.length,
  0
)

export const generatedEnglishReadingQuestionCount = readingSections.reduce(
  (total, section) => total + section.questions.length,
  0
)

export const generatedEnglishWritingQuestionCount = writingSections.reduce(
  (total, section) => total + section.questions.length,
  0
)
