export const DZI_TRANSCRIPT_DIR = '/Users/danielmladenov/Desktop/12-grade-literature-transcripts'

export type DziLiteratureExerciseBlueprint = {
  workId: string
  sourceSlug: string
  genre: string
  primaryTheme: string
  motif: string
  centralFigure: string
  tone: string
}

export const DZI_LITERATURE_EXERCISE_BLUEPRINTS: DziLiteratureExerciseBlueprint[] = [
  {
    workId: 'lit-01',
    sourceSlug: 'zhelezniyat-svetilnik',
    genre: 'роман',
    primaryTheme: 'родът и националното пробуждане',
    motif: 'светилникът',
    centralFigure: 'Султана',
    tone: 'епически и драматичен',
  },
  {
    workId: 'lit-02',
    sourceSlug: 'bay-ganyo-zhurnalist',
    genre: 'фейлетон',
    primaryTheme: 'подмяната на обществените ценности',
    motif: 'вестникът',
    centralFigure: 'Бай Ганьо',
    tone: 'сатиричен и ироничен',
  },
  {
    workId: 'lit-03',
    sourceSlug: 'balkanski-sindrom',
    genre: 'пиеса',
    primaryTheme: 'сблъсъкът между реда и хаоса',
    motif: 'синдромът',
    centralFigure: 'Бай Цончо',
    tone: 'сатиричен и абсурден',
  },
  {
    workId: 'lit-04',
    sourceSlug: 'paisiy',
    genre: 'ода',
    primaryTheme: 'паметта и духовното пробуждане',
    motif: 'искрата',
    centralFigure: 'Паисий',
    tone: 'патетичен и възрожденски',
  },
  {
    workId: 'lit-05',
    sourceSlug: 'istoriya',
    genre: 'стихотворение',
    primaryTheme: 'историята на малкия човек',
    motif: 'историята',
    centralFigure: 'лирическият говорител',
    tone: 'гневен и полемичен',
  },
  {
    workId: 'lit-06',
    sourceSlug: 'noeviyat-kovcheg',
    genre: 'книга',
    primaryTheme: 'спасяването на паметта',
    motif: 'ковчегът',
    centralFigure: 'разказвачът',
    tone: 'притчов и ироничен',
  },
  {
    workId: 'lit-07',
    sourceSlug: 'borba',
    genre: 'стихотворение',
    primaryTheme: 'социалната и нравствената неправда',
    motif: 'борбата',
    centralFigure: 'лирическият говорител',
    tone: 'гневен и бунтовен',
  },
  {
    workId: 'lit-08',
    sourceSlug: 'andreshko',
    genre: 'разказ',
    primaryTheme: 'човечността срещу бездушната власт',
    motif: 'блатото',
    centralFigure: 'Андрешко',
    tone: 'ироничен и социално критичен',
  },
  {
    workId: 'lit-09',
    sourceSlug: 'prikazka-za-stalbata',
    genre: 'приказка',
    primaryTheme: 'нравствената цена на властта',
    motif: 'стълбата',
    centralFigure: 'младият човек',
    tone: 'алегоричен и сатиричен',
  },
  {
    workId: 'lit-10',
    sourceSlug: 'do-moeto-parvo-libe',
    genre: 'стихотворение',
    primaryTheme: 'любовта и революционният дълг',
    motif: 'песента',
    centralFigure: 'лирическият герой',
    tone: 'патетичен и изповеден',
  },
  {
    workId: 'lit-11',
    sourceSlug: 'novoto-grobishte-nad-slivnitsa',
    genre: 'елегия',
    primaryTheme: 'подвигът и паметта',
    motif: 'гробището',
    centralFigure: 'лирическият говорител',
    tone: 'тържествен и скръбен',
  },
  {
    workId: 'lit-12',
    sourceSlug: 'kradetsat-na-praskovi',
    genre: 'повест',
    primaryTheme: 'любовта сред войната',
    motif: 'прасковата',
    centralFigure: 'Елисавета',
    tone: 'лиричен и трагичен',
  },
  {
    workId: 'lit-13',
    sourceSlug: 'pri-rilskiya-manastir',
    genre: 'стихотворение',
    primaryTheme: 'природата като духовен дом',
    motif: 'планината',
    centralFigure: 'лирическият говорител',
    tone: 'възторжен и съзерцателен',
  },
  {
    workId: 'lit-14',
    sourceSlug: 'gradushka',
    genre: 'поема',
    primaryTheme: 'трагизмът на селския труд',
    motif: 'градушката',
    centralFigure: 'селянинът',
    tone: 'драматичен и трагичен',
  },
  {
    workId: 'lit-15',
    sourceSlug: 'spi-ezeroto',
    genre: 'лирическа миниатюра',
    primaryTheme: 'копнежът по хармония',
    motif: 'езерото',
    centralFigure: 'лирическият говорител',
    tone: 'съзерцателен и тих',
  },
  {
    workId: 'lit-16',
    sourceSlug: 'az-iskam-da-te-pomnya-vse-taka',
    genre: 'елегия',
    primaryTheme: 'обречената любов и споменът',
    motif: 'споменът',
    centralFigure: 'лирическият говорител',
    tone: 'нежен и тъжен',
  },
  {
    workId: 'lit-17',
    sourceSlug: 'kolko-si-hubava',
    genre: 'стихотворение',
    primaryTheme: 'възхвалата на любовта и красотата',
    motif: 'красотата',
    centralFigure: 'лирическият говорител',
    tone: 'възторжен и любовен',
  },
  {
    workId: 'lit-18',
    sourceSlug: 'posveshtenie',
    genre: 'стихотворение',
    primaryTheme: 'любовта към живота и свободата',
    motif: 'полетът',
    centralFigure: 'лирическата героиня',
    tone: 'младежки и устремен',
  },
  {
    workId: 'lit-19',
    sourceSlug: 'spasova-mogila',
    genre: 'разказ',
    primaryTheme: 'надеждата пред лицето на страданието',
    motif: 'могилата',
    centralFigure: 'дядо Захари',
    tone: 'трагичен и състрадателен',
  },
  {
    workId: 'lit-20',
    sourceSlug: 'molitva',
    genre: 'стихотворение',
    primaryTheme: 'завръщането към земния живот',
    motif: 'молитвата',
    centralFigure: 'лирическият говорител',
    tone: 'изповеден и смирен',
  },
  {
    workId: 'lit-21',
    sourceSlug: 'vyara',
    genre: 'стихотворение',
    primaryTheme: 'вярата като духовна опора',
    motif: 'вярата',
    centralFigure: 'лирическият говорител',
    tone: 'решителен и обнадежден',
  },
  {
    workId: 'lit-22',
    sourceSlug: 'vetrenata-melnitsa',
    genre: 'разказ',
    primaryTheme: 'трудът и жизнелюбието',
    motif: 'мелницата',
    centralFigure: 'Лазар Дъбака',
    tone: 'жизнерадостен и хумористичен',
  },
  {
    workId: 'lit-23',
    sourceSlug: 'pesenta-na-koleletata',
    genre: 'разказ',
    primaryTheme: 'трудът като творчество и доброта',
    motif: 'колелетата',
    centralFigure: 'Сали Яшар',
    tone: 'лиричен и хуманен',
  },
  {
    workId: 'lit-24',
    sourceSlug: 'balada-za-georg-henih',
    genre: 'повест',
    primaryTheme: 'изкуството като духовно наследство',
    motif: 'цигулката',
    centralFigure: 'Георг Хених',
    tone: 'носталгичен и почтителен',
  },
  {
    workId: 'lit-25',
    sourceSlug: 'dve-dushi',
    genre: 'стихотворение',
    primaryTheme: 'вътрешното раздвоение',
    motif: 'двете души',
    centralFigure: 'лирическият герой',
    tone: 'драматичен и тревожен',
  },
  {
    workId: 'lit-26',
    sourceSlug: 'potomka',
    genre: 'стихотворение',
    primaryTheme: 'родовата памет и свободата',
    motif: 'кръвта',
    centralFigure: 'лирическата героиня',
    tone: 'буен и горд',
  },
  {
    workId: 'lit-27',
    sourceSlug: 'chesten-krast',
    genre: 'стихотворение',
    primaryTheme: 'верността към себе си',
    motif: 'клетвата',
    centralFigure: 'лирическият говорител',
    tone: 'изповеден и категоричен',
  },
]
