const FALLBACK_SUPABASE_URL = 'https://lfxlxoocrdiaucywiavh.supabase.co'
const FALLBACK_SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeGx4b29jcmRpYXVjeXdpYXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMDExNTgsImV4cCI6MjA5MDY3NzE1OH0.sBvY_6FG7TWu7EWienDL7nZIpmAYrOrRqUamhmZyWOA'

export const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? FALLBACK_SUPABASE_URL

export const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? FALLBACK_SUPABASE_ANON_KEY
